### PR TITLE
Probability refactor

### PR DESCRIPTION
**Pull request by bulian-bg**
Increase readability of item generator (AR0602) and planar sphere mage robe script (AR0411).

### CODE REVIEW

**Comment by roman-d** [comment]
So, we actually had a change like that in the past. I've chose to undo it. I did some tests recently, and if you use Continue() the game does not roll a new random number for each subsequent block. This results in suboptimal randomisation. At the very least, I propose to get rid of Continue() calls here.

**Comment by critto-bg** [comment]
So, we actually had a change like that in the past. I've chose to undo it. I did some tests recently, and if you use Continue() the game does not roll a new random number for each subsequent block. This results in suboptimal randomisation. At the very least, I propose to get rid of Continue() calls here.

**Comment by bulian-bg** [comment]
Can you describe the tests?  I'm not sure how that would work.  When I added those a few years ago, the item randomizer results seemed to be randomized in my tests.  As an added bonus, the item randomizer algorithm was essentially instant versus ~1 minute without them, which is a minor quality of life benefit.  Based on how the scripts function (start until a condition is met, restart at top of script), I'm afraid without the continue() line, the script will cycle until the first condition is met on these complicated scenarios that are laid out.  I have some ideas for workarounds if you are confident the continue() is an issue.

**Comment by critto-bg** [comment]
I have no guarantee that my tests are precise, it was more of an educated guess, really.

When we began adding content to Sibel mod, Sikret asked me to add a dialogue branch to a guy in the docks called Celvan. This dude randomly picks one vanilla NPC from your party and says a small limerick about it. You can checkout CELVAN.DLG to see the implementation. It is, essentially, a combination of a 50/50 random roll and DLG state weight factor determining the order of checks.

We observed behavior during testing where he would always fail to make a favorable random roll no matter how many times you reloaded. This has led me to believe that for a cycle of processing (whatever that may be) the engine rolls the random value only once (for it might have been a reasonable optimisation to hit 30 fps on the engine 25 years ago) and uses it many times. And a unique (and unknown) composition of factors seed the randomiser in the same way.

What are these factors, I don't know, it could be anything: current coordinates of the camera view box, character positions, whatever. In my own tests, I tried to move the party around in various ways and managed to get truly randomised results.

All this has led me to suspect that a combination of weidu weight factors inside a script blocks and usage of continue() that forces the engine to do everything in one execution cycle might result in a deterministic "randomless" result even when you init the game anew because some of the starting factors that may or may not affect the randomiser are always the same at the start of the game.

Now, all of this is guesswork based on my experience actually programming random generators. I have no way to find out how they really work inside the game, because I lack the access to the source code nor do I possess the skills to reverse engineer this. The engine does not have any real debugging facilities so the only way to test this for sure is to program a quick save game parser that would extract the variables set by the randomiser and put it into some kind of spreadsheet for further analysis. Then restart the game a few times, feed the saves to the parser and compare the results.

The first test I would do with such a tool is to restart the game with the same character (a vanilla pregenerated one will do) and compare randomiser results generated by your code. If they seem truly random each run then we are lucky and no further testing is needed. If, however, we observe some kind of pattern in random number generation then it merits further experimentation.

This is not a hard task, but one that requires time nonetheless :) Which is why I chose to roll back the changes and postpone them until I have the time to look into this further.

**Comment by bulian-bg** [comment]
Sent an email with some test results

**Pull request closed without merging**
