### PR TITLE
 Update Chinese translation to 7.0 by windmilladventure001

### PR DESCRIPTION
**Pull request by MephistoSatanDevil**
https://github.com/critto-bg/ImprovedAnvil/pull/36#issuecomment-2277168617

### CODE REVIEW

**Comment by critto-bg** [comment]
Can you omit the weidu update, please? It needs to be done and tested separately. Thanks.

**Comment by MephistoSatanDevil** [comment]
> Can you omit the weidu update, please? It needs to be done and tested separately. Thanks.

done.

In fact, when an updated version of weidu.exe exists in the game directory, the file will automatically upgrade itself before installation. So, if there were issues with updating weidu, someone might have already reported the issue. LOL

**Comment by critto-bg** [comment]
Thanks. Yeah, I know about the auto-update thing. Even if everything is fine, I prefer not to mix together different things within one commit. I'll update the weidu separately when I publish a small update, hopefully, this or next week. I'll merge the support for Chinese language into it as well.

**Comment by MephistoSatanDevil** [comment]
> Thanks. Yeah, I know about the auto-update thing. Even if everything is fine, I prefer not to mix together different things within one commit. I'll update the weidu separately when I publish a small update, hopefully, this or next week. I'll merge the support for Chinese language into it as well.

Thank you.

**Comment by MephistoSatanDevil** [comment]
> Thanks. Yeah, I know about the auto-update thing. Even if everything is fine, I prefer not to mix together different things within one commit. I'll update the weidu separately when I publish a small update, hopefully, this or next week. I'll merge the support for Chinese language into it as well.

Thank you.
In fact, we update Weidu.exe because the UTF-8 encoded Chinese console prompts would become garbled under the old version of weidu.exe. The latest version of weidu.exe has resolved this issue, so Chinese modders often update weidu.exe to version 24900 when localizing mods at present.

Some people have discussed this:
https://github.com/The-Gate-Project/DarkHorizons/pull/23
This is another related discussion:
https://github.com/BGforgeNet/bg2-wildmage/issues/30

So updating Weidu.exe is also part of the translation process.

**Comment by critto-bg** [comment]
Understood. I was not aware of this issue. In any case, updating weidu might have some unintended other effect as the result of changes made to the executable. I will need to review what's been done to weidu and make sure there is nothing potentially problematic for us.

**Pull request merged**
