### PR TITLE
Avengers with daggers

### PR DESCRIPTION
**Pull request by bulian-bg**

### CODE REVIEW

**Comment by critto-bg** [comment]
I think that you also need to update the description in setup.tra. Right now it states that the avengers are allowed to specialize in all weapons that are with the "druid domain", and daggers aren't originally a part of that domain.

**Comment by bulian-bg** [comment]
I don't know what you mean by druid domain per se, but my simplistic thinking is that regular druids can use daggers

https://baldursgate.fandom.com/wiki/Druid

**Comment by critto-bg** [comment]
Check out the description for the Avenger kit.

**Comment by bulian-bg** [comment]
I read the description; its not clear to me what the druid domain is (not a D&D person); normal druids in BG2 can use daggers. Not a big deal either way.
     On Friday, June 12, 2020, 06:20:45 AM EDT, critto <notifications@github.com> wrote:  
 
 


Check out the description for the Avenger kit.

**Pull request closed without merging**
