### PR TITLE
Limak chapter 6

### PR DESCRIPTION
**Pull request by bulian-bg**

### CODE REVIEW

**Comment by critto-bg** [comment]
And what is the reason exactly to make him post-underdark? Too difficult?

**Comment by bulian-bg** [comment]
> And what is the reason exactly to make him post-underdark? Too difficult?

Item management.  He has 2x +3 weapons in inventory that are particularly useful pre-spellhold or for crafting.

**Comment by critto-bg** [comment]
OK, fair enough, I'm merge it later. But I can't recall every reading that somebody had tried to defeat him pre-Underdark.

**Comment by critto-bg** [comment]
Merged.

**Pull request closed without merging**
